greeter/config/routes.rb
Greeter::Application.routes.draw do
  resources :greetings  do
    resources :recipients do
      resources :schedule
    end
  end

  devise_for :users

  root :to => 'greetings#index'

end

greeter/app/models/greeting.rb
class Greeting < ActiveRecord::Base
  has_many :greeting_recipients, :dependent => :destroy
  belongs_to :User

  accepts_nested_attributes_for :greeting_recipients, :allow_destroy => :true
         #, :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }

  #scope :find_for_user, lambda { |id, user_id| Greeting.find(id, :conditions => ['users_id = ?', user_id])}

  def self.find_for_user(id, user_id)
    Greeting.find(id, :conditions => ['users_id = ?', user_id])
  end
 
  def self.find_all_for_user(user_id)
     Greeting.all(:conditions => ['users_id = ?', user_id])
  end
  
end

greeter/app/models/greeting_recipient.rb
class GreetingRecipient < ActiveRecord::Base
  belongs_to :greeting
  has_many :greeting_schedules, :dependent => :destroy
  validates_inclusion_of :recipient_type, :in => %w(Email Twitter Facebook)

  accepts_nested_attributes_for :greeting_schedules, :allow_destroy => :true,
         :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }

  RECIPIENT_TYPES = %w(Email Twitter Facebook)
  # def recipient_type
  #     RECIPIENT_TYPES[read_attribute(:recipient_type)]
  #   end
end

greeter/app/models/greeting_schedule.rb
class GreetingSchedule < ActiveRecord::Base
    belongs_to :GreetingRecipient, :class_name => "GreetingRecipient", :foreign_key => "GreetingRecipient_id"
end

greeter/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :greetings, :dependent => :destroy
end

greeter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

greeter/app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  before_filter :authenticate_user!
  # GET /greetings
  # GET /greetings.json
  def index
    @greetings = Greeting.find_all_for_user(current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @greetings }
    end
  end

  # GET /greetings/1
  # GET /greetings/1.json
  def show
    @greeting = Greeting.find_for_user(params[:id], current_user.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @greeting }
    end
  end

  # GET /greetings/new
  # GET /greetings/new.json
  def new
    @greeting = Greeting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @greeting }
    end
  end

  # GET /greetings/1/edit
  def edit
    @greeting = Greeting.find_for_user(params[:id], current_user.id)
  end

  # POST /greetings
  # POST /greetings.json
  def create
    @greeting = Greeting.new(params[:greeting])
    @greeting.users_id = current_user.id
    respond_to do |format|
      if @greeting.save
        format.html { redirect_to @greeting, notice: 'Greeting was successfully created.' }
        format.json { render json: @greeting, status: :created, location: @greeting }
      else
        format.html { render action: "new" }
        format.json { render json: @greeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /greetings/1
  # PUT /greetings/1.json
  def update
    @greeting = Greeting.find_for_user(params[:id], current_user.id)

    respond_to do |format|
      if @greeting.update_attributes(params[:greeting])
        format.html { redirect_to @greeting, notice: 'Greeting was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @greeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /greetings/1
  # DELETE /greetings/1.json
  def destroy
    @greeting = Greeting.find_for_user(params[:id], current_user.id)
    @greeting.destroy

    respond_to do |format|
      format.html { redirect_to greetings_url }
      format.json { head :ok }
    end
  end
end

greeter/app/helpers/application_helper.rb
module ApplicationHelper
end

greeter/app/helpers/greeting_recipient_helper.rb
module GreetingRecipientHelper
end

greeter/app/helpers/greetings_helper.rb
module GreetingsHelper
end

greeter/app/views/greetings/_form.html.erb
<% @greeting.greeting_recipients.build %>
<%= form_for @greeting do |f| %>
  <% if @greeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@greeting.errors.count, "error") %> prohibited this greeting from being saved:</h2>

      <ul>
      <% @greeting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :text, "Greeting" %><br />
  <%= f.text_area :text, :rows => 3 %>


    <%= render :partial => 'recipient',
               :locals => { :form => f, :greeting_recipients => @greeting.greeting_recipients } %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

greeter/app/views/greetings/_recipient.html.erb
<% greeting_recipients.each do |r| %>
	<%= form.fields_for r do |recipient_form| %>
		<div class="field">
			<%= recipient_form.label :recipient, 'Recipient:' %>
			<%= recipient_form.text_field :recipient %>
			<%= recipient_form.label :recipient_type, 'Recipient Type:' %>
			<%= recipient_form.select :recipient_type, options_for_select([['Email', 'Email'], ['Twitter', 'Twitter'], ['Facebook', 'Facebook']], 0) %>
		</div>
		<% unless recipient_form.object.nil? || recipient_form.object.new_record? %>
			<div class="field">
				<%= recipient_form.label :_destroy, 'Remove:' %>
				<%= recipient_form.check_box :_destroy %>
			</div>
		<% end %>

		<%= render :partial => 'schedule',
			:locals => { :form => form, :recipient => r, :schedules => r.greeting_schedules } %>
		
	<% end %>
<% end %>

greeter/app/views/greetings/_schedule.html.erb
<% schedules.each do |s| %>
	<%= form.fields_for s do |schdule_form| %>
		<div class="field">
			<%= schedule_form.label :when, 'When:' %>
			<%= schedule_form.select_datetime :when %>
			<!-- <%= schedule_form.label :recipient_type, 'Recipient Type:' %>
					<%= schedule_form.select :recipient_type, options_for_select([['Email', 'Email'], ['Twitter', 'Twitter'], ['Facebook', 'Facebook']], 0) %> -->
		</div>
		<% unless schedule_form.object.nil? || schedule_form.object.new_record? %>
			<div class="field">
				<%= schedule_form.label :_destroy, 'Remove:' %>
				<%= schedule_form.check_box :_destroy %>
			</div>
		<% end %>
		
	<% end %>
<% end %>

greeter/app/views/greetings/edit.html.erb
<h1>Editing greeting</h1>

<%= render 'form' %>

<%= link_to 'Show', @greeting %> |
<%= link_to 'Back', greetings_path %>

greeter/app/views/greetings/index.html.erb
<h1>Listing greetings</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @greetings.each do |greeting| %>
  <tr>
    <td><%= greeting.text.length > 15 ? greeting.text.slice(0, 15) + "..." : greeting.text %></td>
    <td><%= link_to 'Show', greeting %></td>
    <td><%= link_to 'Edit', edit_greeting_path(greeting) %></td>
    <td><%= link_to 'Destroy', greeting, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Greeting', new_greeting_path %>

greeter/app/views/greetings/new.html.erb
<h1>New greeting</h1>

<%= render 'form' %>

<%= link_to 'Back', greetings_path %>

greeter/app/views/greetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Greeting:</b><br/>
  <pre>
    <%= @greeting.text %>
  </pre>
</p>

<p>
  <b>Recipients:</b><br/>
  <% @greeting.greeting_recipients.each do |recipient| %>
     <%= recipient.recipient %>
     <nbsp/><%= recipient.recipient_type %>
     <p>
        <b>Schedule:</b><br/>
            <% recipient.greeting_schedules.each do |schedule| %>
                <%= schedule.when %>
            <% end %>
  <% end %>
</p>

<%= link_to 'Edit', edit_greeting_path(@greeting) %> |
<%= link_to 'Back', greetings_path %>

greeter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Greeter</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>